// <auto-generated />
using System;
using LibrarySystem.Modules.Books.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibrarySystem.Modules.Books.Infrastructure.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260825122736_AddBookDetailsAndImages")]
    partial class AddBookDetailsAndImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("books")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibrarySystem.Modules.Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Other")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Isbn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("isbn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer")
                        .HasColumnName("published_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.ToTable("books", "books", t =>
                        {
                            t.HasCheckConstraint("ck_books_stock_non_negative", "\"stock\" >= 0");
                        });
                });

            modelBuilder.Entity("LibrarySystem.Modules.Books.Domain.BookImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique()
                        .HasDatabaseName("ux_book_images_book_id_cover")
                        .HasFilter("\"is_cover\" = true");

                    b.HasIndex("BookId", "SortOrder", "Id")
                        .HasDatabaseName("ix_book_images_book_id_sort_order_id");

                    b.ToTable("book_images", "books", t =>
                        {
                            t.HasCheckConstraint("ck_book_images_sort_order_non_negative", "\"sort_order\" >= 0");
                        });
                });

            modelBuilder.Entity("LibrarySystem.Modules.Books.Domain.BookImage", b =>
                {
                    b.HasOne("LibrarySystem.Modules.Books.Domain.Book", null)
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibrarySystem.Modules.Books.Domain.Book", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
